### ISSUE TITLE
spack v0.20.0 does not support "duplicates" keyword in concretizer settings

### ISSUE THREAD

**Issue by briedel** [WIPACrepo/cvmfs#86]
At the moment the concretizer config only works with spack v0.23.0
```
  concretizer:
    targets:
      granularity: generic
      #host_compatible: false
    unify: true
    duplicates:
      strategy: none
```

`duplicates` is not supported in spack v0.20.0
